services:
  api:
    container_name: aws-fastapi
    build:
      context: .
      dockerfile: Dockerfile
    image: fastapi-app:local
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"