services:
  api:
    container_name: aws-fastapi
    build:
      context: .
      dockerfile: Dockerfile
    image: fastapi-app:local
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
    logging:
      driver: "awslogs"
      options:
        awslogs-region: "ap-southeast-1"
        awslogs-group: "/aws/ec2/fastapi-app"
        awslogs-stream: "app"
        awslogs-create-group: "true"